### PR TITLE
Revamp everything: improved performance + subtries

### PR DESCRIPTION
**Pull request by michaelsproul**
This is way faster, and we get shiny new APIs.

### CODE REVIEW

**Comment by michaelsproul** [comment]
This is disturbingly much faster with `rustc 1.14.0-nightly (9c31d76e9 2016-10-03)`.

Old:

```
test benchmark::trie_get           ... bench: 121,716,126 ns/iter (+/- 8,098,068)
test benchmark::trie_insert        ... bench: 143,402,909 ns/iter (+/- 24,101,428)
test benchmark::trie_insert_remove ... bench: 249,433,134 ns/iter (+/- 10,662,332)
```

New:

```
test benchmark::trie_get           ... bench:  30,220,374 ns/iter (+/- 3,973,437)
test benchmark::trie_insert        ... bench:  52,295,969 ns/iter (+/- 4,604,410)
test benchmark::trie_insert_remove ... bench:  81,922,786 ns/iter (+/- 9,844,586)
```

**Comment by andrewcsmith** [comment]
This is very cool. I like what I see so far. One major roadblock is that there is no common trait that both `Trie` and `SubTrie` implement. It would be great to abstract many of the operations so that any a given function can take either struct.

Second, I pushed up a new commit to your new-stuff branch with the changes I had to make in order to get things working with my current library (a voting-experts algorithm library, if you must know). It turned out to be very minimal!

The voting experts part is not the bottleneck of my application, but I'll use it to do some text-segmentation on a fully concatenated version of Moby Dick and let you know if I see a performance improvement there.

**Comment by michaelsproul** [comment]
Great!

Good idea regarding the trait! I think we should also keep `TrieNode` private and just add wrappers for the methods that are currently missing (the iterators, maybe subtries of subtries, but I don't really want to tackle that yet).

**Comment by michaelsproul** [comment]
Those benchmarks from before were using the OS X system allocator, without it, the old code performs a bit better:

## Old

```
test benchmark::trie_get           ... bench:  82,447,514 ns/iter (+/- 5,546,543)
test benchmark::trie_insert        ... bench:  71,935,831 ns/iter (+/- 4,707,764)
test benchmark::trie_insert_remove ... bench: 130,737,040 ns/iter (+/- 34,883,760)
```

## New

```
test benchmark::trie_get           ... bench:  31,841,361 ns/iter (+/- 9,877,950)
test benchmark::trie_insert        ... bench:  34,958,108 ns/iter (+/- 6,714,198)
test benchmark::trie_insert_remove ... bench:  62,985,124 ns/iter (+/- 10,797,948)
```

Ratios are: 2.59 times faster for get, 2.06 for insert, 2.07 for remove.

**Comment by michaelsproul** [comment]
I've added a `TrieCommon` trait that unifies Trie/SubTrie/SubTrieMut. Due to some funky stuff with mutable borrows, there are *two* implementations related to `SubTrieMut`, one for `&'b SubTrieMut<'a, K, V>` from which only values/subtries/etc with lifetime `'b` can be extracted, and one for `SubTrieMut<'a, K, V>` from which values with lifetime `'a` (the original Trie lifetime) can be extracted.

**Comment by michaelsproul** [comment]
The core reason for the difficulty with mutable subtries is that it's impossible to write this function:

```rust
fn borrow<'a: 'b, 'b>(x: &'b &'a mut String) -> &'a String {
    &**x
}
```

The reason for this is that it results in multiple pointers to the underlying string, which violates the property that the `&mut String` is the only reference.

**Comment by andrewcsmith** [comment]
Cool. I'm looking at it, but it's taking a sec. I think I need to redesign bits of my implementation. Sorry—it's very hard for me to stare at code that's as complex as this subtrie borrowing mechanism without implementing something and seeing if it works.

**Comment by michaelsproul** [comment]
Yeah no worries, it's a bit insane the subtrie borrowing thing...

**Comment by andrewcsmith** [comment]
Excellent. It took a little while, but I got everything working without touching the changes you made. I think we're good. At least, I'm satisfied.

I do agree that we need the option of borrowing the key with a `Cow`. I doubt it's going to kill performance at this point, but it would be cool to avoid clones when possible.

I'll try and do the moby dick segmentation pretty soon, to get some benchmarks going with my application.

**Comment by andrewcsmith** [comment]
Hm, I have tests written for all my stuff so I'm not seeing any failures. I don't think I'm working around anything either, but I'm also not matching keys on the `SubTrie`s. (I'm only using the `Children` iterator method.)

[These two methods](https://github.com/andrewcsmith/voting_experts/blob/master/src/trie.rs#L70) (`boundry_entropy` and `boundary_entropy_recur`) are the most difficult parts for me, because of the borrowing.

Incorporating your changes now, and I'll take a closer look when I hack at my own code too.

**Comment by andrewcsmith** [comment]
Now I see your point with the prefix. The changes make sense to me.

I'm going to see what I can do about getting the memory usage down by using `Cow` where possible. It could create some borrow checker hell of course.

Also pushed an example of String frequency evaluation.

**Comment by michaelsproul** [comment]
Ok, gonna merge this to master so we can work on it more easily.

**Pull request merged**
