### PR TITLE
Feature borrow get

### LINKED ISSUE #13: Rewrite `get` to use the Borrow trait.
It'd be nice to be able do lookups with `&str` keys in a `Trie<String, V>`.

### PR DESCRIPTION
**Pull request by roblabla**
Use std::borrow::Borrow for all the methods that use &K.

The feature itself is done, I'm still writing some tests though.

Fixes #13

### CODE REVIEW

**Comment by michaelsproul** [comment]
Looks really nice! The `String`/`&str` tests are great, we don't ever want to lose that feature! 👌

**Comment by michaelsproul** [comment]
Let me know when you feel this is sufficiently tested, and I'll merge it.

It might also be nice to squash a few of the tiny fixup commits

**Comment by roblabla** [comment]
Yup. I was wondering, is there a good way to compare subtries ? Maybe we should implement PartialEq on SubTries ? Cuz the problem is, I'd like to make sure that, for instance, `trie.subtrie("/boot").unwrap() == trie.subtrie(&"/boot").unwrap()` (to make sure we don't treat those differently, just in case. Might be over-testing but... *shrug*).

Anyhow, would it even make sense to implement comparison for subtries ?

**Comment by michaelsproul** [comment]
Sorry it has taken me a while to reply, I think PartialEq for subtries would be fine, just check that the prefix is the same and that iterators over the keys and values return the same thing.

**Comment by michaelsproul** [comment]
I'm inclined to merge this. I'm happy to add a few more tests myself. Sound good?

**Comment by roblabla** [comment]
Sounds good :D

**Pull request merged**
